name: microstack
version: alpha
summary: Openstack on your laptop.
description: |
  Microstack gives you an easy way to develop and test Openstack
  workloads on your laptop. TODO drop in basic usage instructions
  here.
grade: devel
confinement: classic

apps:
  # Keystone
  uwsgi:
    command: snap-openstack keystone-uwsgi
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    daemon: simple
    plugs:
      - network-bind
  nginx:
    command: snap-openstack keystone-nginx
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    daemon: forking
    plugs:
      - network-bind
  manage:
    command: snap-openstack keystone-manage
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    plugs:
      - network

  # Libvirt/Qemu
  libvirt-bin:
    command: bin/launch-libvirtd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    daemon: simple
  virsh:
    command: bin/virsh
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C

parts:
  # Keystone
  keystone:
    plugin: python
    python-version: python2
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/ocata/upper-constraints.txt    
    source: http://tarballs.openstack.org/keystone/keystone-stable-ocata.tar.gz
    python-packages:
      - mysql-python
      - oslo.cache[dogpile]
      - pymysql
      - pysqlite
      - uwsgi
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    install: |
      export PYTHON_PART_INSTALL="/root/build_microstack/parts/keystone/install"
      touch $PYTHON_PART_INSTALL/lib/python2.7/site-packages/paste/__init__.py
      touch $PYTHON_PART_INSTALL/lib/python2.7/site-packages/repoze/__init__.py
      export SNAP_ROOT="../../.."
      export SNAP_SITE_PACKAGES="$PYTHON_PART_INSTALL/lib/python2.7/site-packages"
      patch -d $SNAP_SITE_PACKAGES -p1 < $SNAP_ROOT/patches/oslo-config-dirs.patch
    build-packages:
      - gcc
      - libffi-dev
      - libmysqlclient-dev
      - libssl-dev
      - libsqlite3-dev

  templates:
    after: [keystone]
    plugin: dump
    source: snap

  config:
    after: [keystone]
    plugin: dump
    source: http://tarballs.openstack.org/keystone/keystone-stable-ocata.tar.gz
    organize:
      etc/*.conf: etc/keystone/
      etc/*.ini: etc/keystone/
      etc/*.json: etc/keystone/
      etc/*.templates: etc/keystone/
    filesets:
      etc:
        - etc/keystone/*.conf
        - etc/keystone/*.ini
        - etc/keystone/*.json
        - etc/keystone/*.templates
    stage: [$etc]
    prime: [$etc]
  nginx:
    source: http://www.nginx.org/download/nginx-1.13.0.tar.gz
    plugin: autotools
    configflags:
      - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
      - --http-log-path=/var/snap/keystone/common/log/nginx-access.log
      - --error-log-path=/var/snap/keystone/common/log/nginx-error.log
      - --lock-path=/var/snap/keystone/common/lock/nginx.lock
      - --pid-path=/var/snap/keystone/common/run/nginx.pid
      - --http-client-body-temp-path=/var/snap/keystone/common/lib/nginx_client_body
      - --http-proxy-temp-path=/var/snap/keystone/common/lib/nginx_proxy
      - --http-fastcgi-temp-path=/var/snap/keystone/common/lib/nginx_fastcgi
      - --http-uwsgi-temp-path=/var/snap/keystone/common/lib/nginx_uwsgi
      - --http-scgi-temp-path=/var/snap/keystone/common/lib/nginx_scgi
      - --with-http_ssl_module
    build-packages:
      - libpcre3-dev
      - libssl-dev
      - python-six
    prepare: |
      export SNAP_ROOT="../../.."
      export SNAP_SOURCE="$SNAP_ROOT/parts/nginx/build"
      patch -d $SNAP_SOURCE -p1 < $SNAP_ROOT/patches/drop-nginx-setgroups.patch
  libxml2:
    source: http://xmlsoft.org/sources/libxml2-2.9.4.tar.gz
    plugin: autotools

  # libvirt/qemu
  qemu:
    plugin: nil
    stage-packages:
    - on amd64: [qemu-system-x86]
    - on i386: [qemu-system-x86]
    - on armhf: [qemu-system-arm]
    - on arm64: [qemu-system-arm]
    - qemu-utils
    - libslang2
    organize:
      usr/lib/*/pulseaudio/libpulsecommon-8.0.so: usr/lib/libpulsecommon-8.0.so
      usr/share/seabios/bios-256k.bin: qemu/bios-256k.bin
      usr/share/seabios/vgabios-stdvga.bin: qemu/vgabios-stdvga.bin
      usr/share/seabios/kvmvapic.bin: qemu/kvmvapic.bin
      usr/lib/ipxe/qemu/efi-virtio.rom: qemu/efi-virtio.rom

  kvm-support:
    plugin: nil
    stage-packages:
    - try: [msr-tools]

  libvirt:
    source: .
    source-subdir: libvirt-1.3.1
    plugin: autotools
    build-packages:
    - libxml2-dev
    - libxml-libxml-perl
    - libcurl4-gnutls-dev
    - libncurses5-dev
    - libreadline-dev
    - zlib1g-dev
    - libgcrypt20-dev
    - libgnutls28-dev
    - libyajl-dev
    - libpcap0.8-dev
    - libaudit-dev
    - libdevmapper-dev
    - libpciaccess-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - uuid-dev
    - try: [libnuma-dev]
    - wget
    - dpkg-dev
    stage-packages:
    - dmidecode
    - dnsmasq
    - libxml2
    - libyajl2
    - try: [libnuma1]
    - libcurl3-gnutls
    - libpciaccess0
    configflags:
    - --with-qemu
    - --without-bhyve
    - --without-xen
    - --without-openvz
    - --without-vmware
    - --without-xenapi
    - --without-esx
    - --without-hyperv
    - --without-lxc
    - --without-vz
    - --without-vbox
    - --without-uml
    - --without-sasl
    - --without-storage-iscsi
    - --without-storage-sheepdog
    - --without-storage-rbd
    - --without-storage-lvm
    - --without-selinux
    - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current
    - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - DNSMASQ=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dnsmasq
    - DMIDECODE=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dmidecode
    override-build: |
      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1.orig.tar.gz
      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1-1ubuntu10.24.debian.tar.xz
      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1-1ubuntu10.24.dsc
      dpkg-source -x libvirt*.dsc
      snapcraftctl build
    organize:
      # Hack to shift installed libvirt back to root of snap
      # required to ensure that pathing to files etc works at
      # runtime
      # * is not used to avoid directory merge conflicts
      snap/microstack/current/: ./
