#!/bin/sh
##  The contents of this file are subject to the Mozilla Public License
##  Version 1.1 (the "License"); you may not use this file except in
##  compliance with the License. You may obtain a copy of the License
##  at http://www.mozilla.org/MPL/
##
##  Software distributed under the License is distributed on an "AS IS"
##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
##  the License for the specific language governing rights and
##  limitations under the License.
##
##  The Original Code is RabbitMQ.
##
##  The Initial Developer of the Original Code is GoPivotal, Inc.
##  Copyright (c) 2007-2014 GoPivotal, Inc.  All rights reserved.
##

mkdir -p $SNAP_COMMON/lib/rabbitmq
cd $SNAP_COMMON/lib/rabbitmq

SCRIPT=`basename $0`

case $SCRIPT in
    rabbitmq-server)
        mkdir -p $SNAP_COMMON/log/rabbitmq
        $SNAP/usr/lib/rabbitmq/bin/rabbitmq-server "$@" \
            > "$SNAP_COMMON/log/rabbitmq/startup_log" \
            2> "$SNAP_COMMON/log/rabbitmq/startup_err"
    ;;
    *)
        $SNAP/usr/lib/rabbitmq/bin/${SCRIPT} "$@"
    ;;
esac
