#!/bin/bash
# Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

if [ -f "${SNAP_USER_COMMON}/conf/my.cnf" ];
then
  MYSQL_CONFFILE="${SNAP_USER_COMMON}/conf/my.cnf"
elif [ -f "${SNAP_COMMON}/conf/my.cnf" ];
then
  MYSQL_CONFFILE="${SNAP_COMMON}/conf/my.cnf"
else
  echo "WARNING: Can't find config file. Did you run mysql.startup?"
fi 

if [ -f ${MYSQL_CONFFILE} ];
then
  echo "Using config file: ${MYSQL_CONFFILE}"
  MYSQL_CONFPARAM="--defaults-file=${MYSQL_CONFFILE}"
fi
mysql "${MYSQL_CONFPARAM}" $@
